version: 0.2

env:
  variables:
    ARTIFACTS_BUCKET: "file-manager-s3"
    REGION: us-east-1
    STACK_NAME: file-manager-stack
  secrets-manager:
    GITHUB_NPM_TOKEN: arn:aws:secretsmanager:us-east-1:775504574021:secret:NPM_TOKEN-VzDA41:NPM_TOKEN

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Install Prequisites"
      - npm config set @firme-app:registry https://npm.pkg.github.com # <- replace OWNER with the organization/owner name
      - npm config set //npm.pkg.github.com/:_authToken $GITHUB_NPM_TOKEN
      - n stable
      - npm install -g npm@9
  pre_build:
    commands:
      - npm ci
      - echo "setup profile"
      - . ./buildspecs/aws-profile-setup.sh
      - . ./buildspecs/aws-create-bucket.sh
  build:
    commands:
      - npm run build:production
  post_build:
    commands:
      - echo "Start build"
      - aws cloudformation package --template-file .aws-sam/build/template.yaml --region ${REGION} --s3-bucket "${ARTIFACTS_BUCKET}-${TARGET_ACCOUNT_ID}" --output-template-file stack.yaml
      - sam deploy --stack-name ${STACK_NAME} --role-arn arn:aws:iam::${TARGET_ACCOUNT_ID}:role/cf-execution-role-serverless --template ./stack.yaml --capabilities CAPABILITY_IAM --region ${REGION} --s3-bucket "${ARTIFACTS_BUCKET}-${TARGET_ACCOUNT_ID}" --no-fail-on-empty-changeset
artifacts:
  files:
    - stack.yaml
cache:
  paths:
    - "node_modules/**/*"
